image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - deployment/
    expire_in: 1 day

aws-deploy:
  image: python
  stage: deploy
  script:
    - "cd /builds/soumojitd"
    - "ls -ltr"