image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DEPLOYMENT_FILE: "aws-demo.jar"

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B -DdeploymentFile=$DEPLOYMENT_FILE"
  artifacts:
    paths:
      - $DEPLOYMENT_FILE
    expire_in: 1 hour

aws-deploy:
  image: python
  stage: deploy
  script:
    - "pip3 install awscli --upgrade"
    - "aws --version"
    - "aws lambda update-function-code --function-name DemoAppLambdaFunction --zip-file fileb://$DEPLOYMENT_FILE"