stages:
  - build
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/deployment/*.jar

aws-deploy:
  image: frolvlad:alpine-python3
  stage: deploy
  script:
    - "pip install awscli --upgrade"
    - "aws --version"