image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  JAR_NAME: "aws-demo"
  DEPLOYMENT_FILE: "./target/$JAR_NAME-runner.jar"

maven-build:
  only:
    refs:
      - master
  image: maven:3-jdk-11
  stage: build
  script: "mvn package -B -DjarName=$JAR_NAME"
  artifacts:
    paths:
      - $DEPLOYMENT_FILE
    expire_in: 1 hour

aws-deploy:
  only:
    refs:
      - master
  image: python
  stage: deploy
  script:
    - "pip3 install awscli --upgrade"
    - "aws --version"
    - "aws lambda update-function-code --function-name $AWS_LAMBDA_FUNCTION_NAME --zip-file fileb://$DEPLOYMENT_FILE"